### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by ZitaNemeckova** [RoadToSoftwareFactory/swi1-2017#4]
Checklist:
- [ ] no extra files
  - Delete controller file when you move it.
  - No extra files like backup or any config files.
- [ ]  convert new and edit (if it applies to you)
  - if you changed only edit or new you should convert the other one too
- [ ] use bindings not `ManageIQ.angular.app.value('something', @something);`
  - change from`ManageIQ.angular.app.value('something', @something);` to `%some-component{'something' => @something}` **but use names from your files**
[See here](https://github.com/ManageIQ/manageiq-ui-classic/pull/3514/commits/cd54589e9772c1e3d8c952359b4ff2fdc590ff70)
- [ ] controller is in component file
  - see this [commit](https://github.com/ManageIQ/manageiq-ui-classic/pull/3514/commits/65ea5e2f8872cc8d239b63d6ea1a06e2bee9cbd3) to see how to do it. **Do not copy anything from there.**
- [ ] network.rb isn't changed
  - any change to `network.rb` is wrong. If you don't know how to remove it or you have more changes in commit that adds it make new commit where you only remove the changes. Or rebase.
- [ ] only one new file in `views/static/`
- [ ] no Ruby variables in `views/static/`
   - anything with `@` or local Ruby variable should be passed via `bindings`, `controller_name` as well
- [ ] using `repository` anywhere is big no-no.
